openapi: 3.0.0
info:
  title: JUST EAT /
  version: 1.0.0
servers:
  - url: https://test.xntproject.com
  - url: https://test.xntproject.com/api/v1
  - url: http://localhost:8700
  - url: http://107.21.164.101:8700
tags:
  - name: vendor control
  - name: products
  - name: Admin/
  - name: Admin/ > CATEGORY
  - name: Admin/ > SUB-CATEGORY
  - name: Admin/ > admin login
  - name: Admin/ > vendor control
  - name: Admin/ > user control
  - name: usercontrol
paths:
  /api/v1/justeat/addrestaurant/:
    post:
      tags:
        - vendor control
      summary: add Restaurent
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                restaurant_name: ABCsdsdssdsd
                restaurant_address: ABC plazap
                pincode: '11'
                confirm_email: kl099
                email: kl099
                meal_timming: breakfast
                contact_number: '99'
                first_name: deepak
                last_name: sharma
                primary_cuisine: hello
                secoundry_cuisine: hye
                address_of_welcome_pack: regular malll pink square
                business_operate: basement
                typeof_location: interna
                drivers_availability: jjjjj
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/v1/justeat/addrestaurant:
    post:
      tags:
        - vendor control
      summary: add additional info
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                restaurant_name: ABCsdsdssdsd
                restaurant_address: ABC plazap
                pincode: '11'
                confirm_email: kl099
                email: kl099
                meal_timming: breakfast
                contact_number: '99'
                first_name: deepak
                last_name: sharma
                primary_cuisine: hello
                secoundry_cuisine: hye
                address_of_welcome_pack: regular malll pink square
                business_operate: basement
                typeof_location: interna
                drivers_availability: jjjjj
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/v1/justeat/verification/62e94e2f24fbbc2658d61885:
    put:
      tags:
        - vendor control
      summary: ownership verification
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                email:
                  type: string
                  example: kkk
                photo_id:
                  type: string
                  format: binary
                proof_of_ownership:
                  type: string
                  format: binary
                shop_image_front:
                  type: string
                  format: binary
                foot_hygiene_registration:
                  type: string
                  format: binary
                permission_to_trade:
                  type: string
                  format: binary
                menu:
                  type: string
                  format: binary
                restaurant_logo:
                  type: string
                  format: binary
                address_of_welcome_pack:
                  type: string
                  example: jjjjjjj
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/v1/justeat/bank_details/62e907c88c7ad0c24291706f:
    put:
      tags:
        - vendor control
      summary: bankdetails
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                address_of_welcome_pack↵: jjjkkkk
                account_holder_name: jjjhh
                account_number: jjjhbh
                bank_name: juhuh
                sort_code: jjjjuhuh
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/v1/justeat/updaterestaurant/62e375d1258462fb1cfb037c:
    put:
      tags:
        - vendor control
      summary: UPDATE RESTURENT
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                restaurant_name:
                  type: string
                  example: ABCsdsdssdsd
                restaurant_address:
                  type: string
                  example: ABC plaza
                contact_number:
                  type: integer
                  example: '08'
                email:
                  type: string
                  example: ',phh,kkllnkkkkbbbcc'
                first_name:
                  type: string
                  example: deepak
                last_name:
                  type: string
                  example: sharma
                primary_cuisine:
                  type: string
                  example: hellolll
                secoundry_cuisine:
                  type: string
                  example: hye
                address_of_welcome_pack:
                  type: string
                  example: regular malll pink square
                bussiness_operate:
                  type: string
                  example: basement
                typeof_location:
                  type: string
                  example: internakk
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/v1/justeat/login_vendor:
    get:
      tags:
        - vendor control
      summary: LOGIN
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/v1/justeat/logout:
    get:
      tags:
        - usercontrol
      summary: logout/user
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/v1/justeat/deleteretaurant/62e2607e213d010797e7614a:
    delete:
      tags:
        - vendor control
      summary: DELETE RESTURENT
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/v1/justeat/create_menu/62ea8da82dd2bfc4aa0bfe18:
    post:
      tags:
        - products
      summary: create_menu
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                Product_name:
                  type: string
                  example: rasgulla
                Product_description:
                  type: string
                  example: seet and cherry
                price:
                  type: string
                  example: '100 '
                quantity:
                  type: integer
                  example: '50'
                image:
                  type: string
                  format: binary
                offer_price:
                  type: integer
                  example: '80'
                item_name:
                  type: string
                  example: bengali
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/v1/justeat/get_products/62e36fc3c1d59716c4f0da5c:
    get:
      tags:
        - products
      summary: getallproducts
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/v1/admin/addcategory:
    post:
      tags:
        - Admin/ > CATEGORY
      summary: ADD
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                category_name:
                  type: string
                  example: Deserthvhvh
                restaurant_id:
                  type: string
                  example: 62ea3c66c2fe73de6aa5db6f
                image:
                  type: string
                  format: binary
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /admin/updatecategory/62d13d78d82891addf1fbcc1:
    put:
      tags:
        - Admin/ > CATEGORY
      summary: UPDATE
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                category_name:
                  type: string
                  example: eastee
                category_id:
                  type: integer
                  example: '556555'
                image:
                  type: string
                  format: binary
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /admin/getcategorydetails:
    get:
      tags:
        - Admin/ > CATEGORY
      summary: GET ALL
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /admin/deletecategory/62d50c882b47a20ca807d48f:
    delete:
      tags:
        - Admin/ > CATEGORY
      summary: DELETE
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /admin/addsubcategory:
    post:
      tags:
        - Admin/ > SUB-CATEGORY
      summary: ADD
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                sub_category_name:
                  type: string
                  example: madhavkkjj
                image:
                  type: string
                  format: binary
                category:
                  type: string
                  example: 62e2646b213d010797e76152
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/v1/admin/updatesubcategory/62e76a718fd92ec982ea1a22:
    put:
      tags:
        - Admin/ > SUB-CATEGORY
      summary: UPDATE
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                sub_category_name:
                  type: string
                  example: madhavkklllllllllllllllllllllllllll
                image:
                  type: string
                  format: binary
      parameters:
        - name: Authorization
          in: header
          schema:
            type: string
          example: >-
            bearer
            eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RAMTIiLCJpZCI6IjYyZGUzNmExMDcyNGMyMmQyYmU1MmMwNSIsInBhc3N3b3JkIjoiMTIzNCIsImlhdCI6MTY1ODgxNTQzMX0.MjrssS8_5tYxC2OrRLRg1kvkXKcSDxDpxK8_vDtXexA
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /admin/getsubcategorydetails:
    get:
      tags:
        - Admin/ > SUB-CATEGORY
      summary: GET ALL
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /justeat/deletesubcategory/62cfaccf4441b9425937720a:
    delete:
      tags:
        - Admin/ > SUB-CATEGORY
      summary: DELETE
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /admin/signup:
    post:
      tags:
        - Admin/ > admin login
      summary: admin/signup
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                email: admin
                password: '123'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/v1/admin/login:
    post:
      tags:
        - Admin/ > admin login
      summary: admin/login
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                email: admin
                password: '123'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/v1/admin/change_password:
    put:
      tags:
        - Admin/ > admin login
      summary: admin/changepassword
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                new_Password: '123'
                current_Password: '1234'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /admin/getrestaurants:
    get:
      tags:
        - Admin/ > vendor control
      summary: gell all restaurant
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /admin/getusers:
    get:
      tags:
        - Admin/ > user control
      summary: get users
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/v1/justeat/adduser:
    post:
      tags:
        - usercontrol
      summary: adduser
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                firstname: majdhjjjjjjav
                lastname: req.body.lastname
                email: yojjjjjgijkkjj
                address: dfdjfkajf
                password: '9999'
                status: true
                is_registered: 'true'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/v1/justeat/cart:
    post:
      tags:
        - usercontrol
      summary: cart
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                productId: 62ea415fab797da1d0778946
                quantity: '2'
                name: jj
                price: '000'
                offer_price: '000'
                type: user
                vendorId: 62e36fc3c1d59716c4f0da5c
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/v1/justeat/updateuser/62e79697cf6f6f267266f03c:
    patch:
      tags:
        - usercontrol
      summary: update user
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                firstname: r
                lastname: r
                email: rohjjjjkjit
                address: ooklllkkkkkkko
                status: true
                is_registered: 'true'
                user_type: 'true'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/v1/justeat/login_user:
    post:
      tags:
        - usercontrol
      summary: login/user
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                email: yojjjjjgijkkjj
                password: '9999'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/v1/justeat/deleteuser/62e26a88213d010797e76168:
    delete:
      tags:
        - usercontrol
      summary: Delete user
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/v1/justeat/searchbypin/11:
    get:
      tags:
        - usercontrol
      summary: search_restro_byid
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/v1/justeat/Searchbymealtimming/break:
    get:
      tags:
        - usercontrol
      summary: Searchby_mealtimming
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
